name: Stage-2 BlueGreen Verification

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.24
        options: --privileged
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin docker.io perl
          docker --version
          docker compose version

      - name: Copy example env (CI should override with grader env)
        run: cp .env.example .env

      - name: Start stack
        run: |
          chmod +x start.sh
          ./start.sh
          sleep 2

      - name: Baseline check via nginx
        run: |
          sleep 1
          curl -s -D - http://localhost:8080/version -o /tmp/version_out || true
          grep -i "HTTP/" /tmp/version_out || true
          grep -i "X-App-Pool" /tmp/version_out || true
          grep -i "X-Release-Id" /tmp/version_out || true

      - name: Trigger chaos on blue
        run: |
          curl -s -X POST "http://localhost:8081/chaos/start?mode=error" || true
          sleep 0.5

      - name: Run multiple requests and assert
        run: |
          PASS=0
          for i in $(seq 1 20); do
            HEADERS=$(curl -s -D - http://localhost:8080/version -o /dev/null)
            echo "$i -> $(echo "$HEADERS" | egrep -i 'X-App-Pool|HTTP/' | tr '\n' ' ')"
            echo "$HEADERS" | egrep -i 'HTTP/.*200' || { echo "Non-200 detected"; exit 1; }
            echo "$HEADERS" | egrep -i 'X-App-Pool: green' || true
            PASS=$((PASS+1))
            sleep 0.25
          done
          echo "Requests done: $PASS"

      - name: Stop chaos on blue
        run: |
          curl -s -X POST "http://localhost:8081/chaos/stop" || true

      - name: Tear down
        run: docker-compose down -v
